import type { Recipe } from './types';

/** Craving tags the user can pick from when planning the week. */
export const CRAVINGS = [
  'comfort',
  'asian',
  'mexican',
  'italian',
  'healthy',
  'high-protein',
  'quick',
  'spicy',
] as const;

/**
 * A small library of cheap, student-friendly recipes. Costs are rough per-serving
 * estimates in dollars — the point is to budget by them, not to be exact.
 *
 * `contains` lists dietary attributes (meat/dairy/gluten/high-carb/…) that diets
 * filter against — see `src/lib/plan/diets.ts`.
 */
export const RECIPES: Recipe[] = [
  // --- breakfast ----------------------------------------------------------
  {
    id: 'r-oats',
    title: 'Oats & banana',
    emoji: '🥣',
    slots: ['breakfast'],
    cost: 0.8,
    calories: 350,
    health: 'high fiber · slow-release energy',
    cheap: true,
    tags: ['healthy', 'quick', 'comfort'],
    contains: ['dairy', 'gluten', 'high-carb'],
    ingredients: [
      { name: 'rolled oats', qty: '1/2 cup', cost: 0.3 },
      { name: 'banana', qty: '1', cost: 0.25 },
      { name: 'milk', qty: '1 cup', cost: 0.25 },
    ],
  },
  {
    id: 'r-eggtoast',
    title: 'Eggs on toast',
    emoji: '🍳',
    slots: ['breakfast', 'lunch'],
    cost: 1.1,
    calories: 400,
    health: 'complete protein · keeps you full',
    cheap: true,
    tags: ['high-protein', 'quick', 'comfort'],
    contains: ['egg', 'dairy', 'gluten', 'high-carb'],
    ingredients: [
      { name: 'eggs', qty: '2', cost: 0.6 },
      { name: 'bread', qty: '2 slices', cost: 0.4 },
      { name: 'butter', qty: '1 tsp', cost: 0.1 },
    ],
  },
  {
    id: 'r-pbtoast',
    title: 'Peanut butter toast',
    emoji: '🥜',
    slots: ['breakfast'],
    cost: 0.6,
    calories: 380,
    health: 'plant protein · healthy fats',
    cheap: true,
    tags: ['quick', 'comfort', 'high-protein'],
    contains: ['gluten', 'high-carb'],
    ingredients: [
      { name: 'bread', qty: '2 slices', cost: 0.4 },
      { name: 'peanut butter', qty: '2 tbsp', cost: 0.2 },
    ],
  },
  {
    id: 'r-yogurt',
    title: 'Yogurt & oats bowl',
    emoji: '🥄',
    slots: ['breakfast'],
    cost: 1.2,
    calories: 320,
    health: 'probiotics · protein',
    cheap: false,
    tags: ['healthy', 'quick'],
    contains: ['dairy', 'gluten', 'high-carb'],
    ingredients: [
      { name: 'yogurt', qty: '1 cup', cost: 0.8 },
      { name: 'rolled oats', qty: '1/4 cup', cost: 0.15 },
      { name: 'frozen berries', qty: '1/4 cup', cost: 0.25 },
    ],
  },

  // --- lunch / dinner -----------------------------------------------------
  {
    id: 'r-riceandbeans',
    title: 'Rice & beans',
    emoji: '🍚',
    slots: ['lunch', 'dinner'],
    cost: 1.0,
    calories: 520,
    health: 'complete protein · high fiber',
    cheap: true,
    tags: ['mexican', 'comfort', 'healthy', 'high-protein'],
    contains: ['high-carb'],
    ingredients: [
      { name: 'rice', qty: '1 cup', cost: 0.3 },
      { name: 'canned beans', qty: '1/2 can', cost: 0.5 },
      { name: 'onion', qty: '1/2', cost: 0.2 },
    ],
  },
  {
    id: 'r-beanwrap',
    title: 'Bean & cheese wrap',
    emoji: '🌯',
    slots: ['lunch'],
    cost: 1.6,
    calories: 480,
    health: 'fiber · calcium',
    cheap: true,
    tags: ['mexican', 'quick', 'comfort'],
    contains: ['dairy', 'gluten', 'high-carb'],
    ingredients: [
      { name: 'tortilla', qty: '1', cost: 0.4 },
      { name: 'canned beans', qty: '1/2 can', cost: 0.5 },
      { name: 'cheese', qty: '30g', cost: 0.5 },
      { name: 'salsa', qty: '2 tbsp', cost: 0.2 },
    ],
  },
  {
    id: 'r-pasta',
    title: 'Tomato veg pasta',
    emoji: '🍝',
    slots: ['lunch', 'dinner'],
    cost: 1.4,
    calories: 600,
    health: 'lycopene · energy',
    cheap: true,
    tags: ['italian', 'comfort'],
    contains: ['gluten', 'high-carb'],
    ingredients: [
      { name: 'pasta', qty: '100g', cost: 0.4 },
      { name: 'canned tomatoes', qty: '1/2 can', cost: 0.5 },
      { name: 'onion', qty: '1/2', cost: 0.2 },
      { name: 'frozen veg', qty: '1/2 cup', cost: 0.3 },
    ],
  },
  {
    id: 'r-stirfry',
    title: 'Veg & egg fried rice',
    emoji: '🍳',
    slots: ['lunch', 'dinner'],
    cost: 1.5,
    calories: 560,
    health: 'protein · veg serving',
    cheap: true,
    tags: ['asian', 'quick', 'comfort'],
    contains: ['egg', 'gluten', 'high-carb'],
    ingredients: [
      { name: 'rice', qty: '1 cup', cost: 0.3 },
      { name: 'eggs', qty: '2', cost: 0.6 },
      { name: 'frozen veg', qty: '1 cup', cost: 0.4 },
      { name: 'soy sauce', qty: '1 tbsp', cost: 0.1 },
    ],
  },
  {
    id: 'r-noodlesoup',
    title: 'Loaded noodle soup',
    emoji: '🍜',
    slots: ['lunch', 'dinner'],
    cost: 1.3,
    calories: 450,
    health: 'hydrating · add-an-egg protein',
    cheap: true,
    tags: ['asian', 'spicy', 'comfort', 'quick'],
    contains: ['egg', 'gluten', 'high-carb'],
    ingredients: [
      { name: 'instant noodles', qty: '1 pack', cost: 0.4 },
      { name: 'egg', qty: '1', cost: 0.3 },
      { name: 'frozen veg', qty: '1/2 cup', cost: 0.3 },
      { name: 'chili oil', qty: '1 tsp', cost: 0.3 },
    ],
  },
  {
    id: 'r-curry',
    title: 'Chickpea curry',
    emoji: '🍛',
    slots: ['dinner'],
    cost: 1.8,
    calories: 580,
    health: 'plant protein · fiber · iron',
    cheap: true,
    tags: ['spicy', 'healthy', 'comfort', 'high-protein'],
    contains: ['high-carb'],
    ingredients: [
      { name: 'canned chickpeas', qty: '1 can', cost: 0.8 },
      { name: 'canned tomatoes', qty: '1/2 can', cost: 0.5 },
      { name: 'onion', qty: '1', cost: 0.3 },
      { name: 'curry powder', qty: '1 tbsp', cost: 0.2 },
    ],
  },
  {
    id: 'r-tacos',
    title: 'Black bean tacos',
    emoji: '🌮',
    slots: ['dinner'],
    cost: 2.0,
    calories: 540,
    health: 'fiber · plant protein',
    cheap: false,
    tags: ['mexican', 'spicy', 'comfort'],
    contains: ['dairy', 'gluten', 'high-carb'],
    ingredients: [
      { name: 'tortilla', qty: '3', cost: 0.9 },
      { name: 'canned beans', qty: '1/2 can', cost: 0.5 },
      { name: 'cheese', qty: '30g', cost: 0.5 },
      { name: 'salsa', qty: '3 tbsp', cost: 0.1 },
    ],
  },
  {
    id: 'r-chickenbowl',
    title: 'Chicken & rice bowl',
    emoji: '🍗',
    slots: ['lunch', 'dinner'],
    cost: 2.6,
    calories: 620,
    health: 'lean protein · balanced',
    cheap: false,
    tags: ['high-protein', 'healthy', 'comfort'],
    contains: ['poultry', 'gluten', 'high-carb'],
    ingredients: [
      { name: 'chicken thigh', qty: '120g', cost: 1.6 },
      { name: 'rice', qty: '1 cup', cost: 0.3 },
      { name: 'frozen veg', qty: '1 cup', cost: 0.4 },
      { name: 'soy sauce', qty: '1 tbsp', cost: 0.1 },
    ],
  },
  {
    id: 'r-lentilsoup',
    title: 'Lentil soup',
    emoji: '🥣',
    slots: ['lunch', 'dinner'],
    cost: 1.2,
    calories: 420,
    health: 'iron · fiber · very filling',
    cheap: true,
    tags: ['healthy', 'comfort', 'high-protein'],
    contains: ['high-carb'],
    ingredients: [
      { name: 'red lentils', qty: '1/2 cup', cost: 0.5 },
      { name: 'carrot', qty: '1', cost: 0.2 },
      { name: 'onion', qty: '1/2', cost: 0.2 },
      { name: 'stock cube', qty: '1', cost: 0.3 },
    ],
  },
  {
    id: 'r-bigsalad',
    title: 'Big crunchy salad',
    emoji: '🥗',
    slots: ['lunch'],
    cost: 2.2,
    calories: 380,
    health: 'micronutrients · light',
    cheap: false,
    tags: ['healthy'],
    contains: [],
    ingredients: [
      { name: 'mixed greens', qty: '2 cups', cost: 1.0 },
      { name: 'canned chickpeas', qty: '1/2 can', cost: 0.4 },
      { name: 'cucumber', qty: '1/2', cost: 0.4 },
      { name: 'dressing', qty: '1 tbsp', cost: 0.4 },
    ],
  },
  {
    id: 'r-grilledcheese',
    title: 'Grilled cheese & soup',
    emoji: '🧀',
    slots: ['lunch', 'dinner'],
    cost: 1.5,
    calories: 560,
    health: 'comfort · calcium',
    cheap: true,
    tags: ['comfort', 'italian', 'quick'],
    contains: ['dairy', 'gluten', 'high-carb'],
    ingredients: [
      { name: 'bread', qty: '2 slices', cost: 0.4 },
      { name: 'cheese', qty: '40g', cost: 0.6 },
      { name: 'canned tomato soup', qty: '1/2 can', cost: 0.5 },
    ],
  },
  {
    id: 'r-bakedpotato',
    title: 'Loaded baked potato',
    emoji: '🥔',
    slots: ['dinner'],
    cost: 1.3,
    calories: 500,
    health: 'potassium · fiber (skin on)',
    cheap: true,
    tags: ['comfort', 'healthy'],
    contains: ['dairy', 'high-carb'],
    ingredients: [
      { name: 'potato', qty: '1 large', cost: 0.4 },
      { name: 'canned beans', qty: '1/2 can', cost: 0.5 },
      { name: 'cheese', qty: '25g', cost: 0.4 },
    ],
  },
];

export const RECIPES_BY_ID: Record<string, Recipe> = Object.fromEntries(
  RECIPES.map((r) => [r.id, r]),
);

/**
 * Make a user-created recipe resolvable by id everywhere `RECIPES_BY_ID` is read
 * (dish detail, cookbook, plan, shopping). The `RecipeProvider` calls this on
 * load and whenever a recipe is created.
 */
export function registerUserRecipe(recipe: Recipe): void {
  RECIPES_BY_ID[recipe.id] = recipe;
}
